# Generated by Django 5.0.4 on 2024-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
